%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\ttsh\OneDrive\Python Code\Vehicle Model\LBORO\Vehicle Model\RealData\realcycle_kph_out.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/04/23 13:51:33

%% Initialize variables.
filename = 'C:\Users\ttsh\OneDrive\Python Code\Vehicle Model\LBORO\Vehicle Model\RealData\realcycle_kph_out.csv';
delimiter = ',';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
t = dataArray{:, 1};
SpeedTgt = dataArray{:, 2};
Speed = dataArray{:, 3};
Mode = dataArray{:, 4};
isGen = dataArray{:, 5};
Faero = dataArray{:, 6};
SpeedE = dataArray{:, 7};
SpeedP = dataArray{:, 8};
SpeedI = dataArray{:, 9};
SpeedD = dataArray{:, 10};
MotorE = dataArray{:, 11};
MotorP = dataArray{:, 12};
MotorI = dataArray{:, 13};
MotorD = dataArray{:, 14};
BrakeE = dataArray{:, 15};
BrakeP = dataArray{:, 16};
BrakeI = dataArray{:, 17};
BrakeD = dataArray{:, 18};
VoltB = dataArray{:, 19};
VoltE = dataArray{:, 20};
VoltM = dataArray{:, 21};
AmpB = dataArray{:, 22};
AmpE = dataArray{:, 23};
AmpM = dataArray{:, 24};
TqM = dataArray{:, 25};
TqAx = dataArray{:, 26};
TqW0 = dataArray{:, 27};
TqW2 = dataArray{:, 28};
TqB0 = dataArray{:, 29};
TqB2 = dataArray{:, 30};
WM = dataArray{:, 31};
WAx = dataArray{:, 32};
WW0 = dataArray{:, 33};
WW2 = dataArray{:, 34};
WB0 = dataArray{:, 35};
WB2 = dataArray{:, 36};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;